## POLICY EVALUATION IN GRID WORLD

In [1]:
import numpy as np
import sys
sys.path.append('./env')
from gridworld import GridworldEnv
print ("PACKAGES LOADED.")

PACKAGES LOADED.


## INITIALIZE GRID WORLD ENVIRONMENT

In [2]:
env = GridworldEnv()
print ("GRID WORLD INITIALIZED.")
print ("#STATE: %d / #ACTION: %d" % (env.nS, env.nA))

GRID WORLD INITIALIZED.
#STATE: 16 / #ACTION: 4


## POLICY EVALUATION

In [3]:
def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    """
    Evaluate a policy given an environment and a full description of the environment's dynamics.
    Args:
        policy: [S, A] shaped matrix representing the policy.
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a (prob, next_state, reward, done) tuple.
        theta: Stopping criteria
        discount_factor: lambda discount factor.
    Returns:
        Vector of length env.nS representing the value function.
    """
    # Start with a random (all 0) value function
    V = np.zeros(env.nS)
    while True:
        delta = 0
        # For each state, perform a "full backup"
        for s in range(env.nS):
            v = 0
            # Look at the possible next actions
            for a, action_prob in enumerate(policy[s]):
                # For each action, look at the possible next states...
                for  prob, next_state, reward, done in env.P[s][a]:
                    # Calculate the expected value
                    v += action_prob * prob * (reward + discount_factor * V[next_state])
            # How much our value function changed (across any states)
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v
        # Stop evaluating once our value function change is below a threshold
        if delta < theta:
            break
    return np.array(V)

## MAKE RANDOM POLICY AND EVALUATE

In [4]:
random_policy = np.ones([env.nS, env.nA]) / env.nA
v = policy_eval(random_policy, env)

## PRINT RESULTS

In [5]:
print("Reshaped Grid Value Function:")
print(v.reshape(env.shape))

Reshaped Grid Value Function:
[[  0.         -13.99993529 -19.99990698 -21.99989761]
 [-13.99993529 -17.9999206  -19.99991379 -19.99991477]
 [-19.99990698 -19.99991379 -17.99992725 -13.99994569]
 [-21.99989761 -19.99991477 -13.99994569   0.        ]]
